### ISSUE TITLE
The album information is always required?

### ISSUE THREAD

**Issue by yannickoo** [bahamas10/node-musicnamer#2]
I configured my `.musicnamer.json` file to use this format: `:artist/:title.:ext` – that doesn't require an album name but I cannot rename a file without the album information because of [this](https://github.com/bahamas10/node-musicnamer/blob/master/bin/musicnamer.js#L56) line.

 BTW thank you for this great tool, it feels so good to get rid of Mp3tag :)

**Comment by bahamas10** [comment]
ah interesting... good point.  I'll take a look at this

**Comment by bahamas10** [comment]
```
$ npm publish
+ musicnamer@0.2.4
```

should work now!
